language: ruby
cache: bundler
rvm:
  - "2.3.0"
  - "2.2"
  - "2.1"
  - "2.0"
  - "jruby-9.1.5.0"

jdk:
  - oraclejdk7
  - oraclejdk8

env:
  - JRUBY_OPTS=--debug

sudo: false

services:
  - rabbitmq

matrix:
  include:
    - rvm: 2.3.0
      jdk: oraclejdk7
    - rvm: 2.2
      jdk: oraclejdk7
    - rvm: 2.1
      jdk: oraclejdk7
    - rvm: 2.0
      jdk: oraclejdk7
    - rvm: jruby-9.1.5.0
      jdk: oraclejdk8
