language: ruby
cache: bundler
before_install:
  - gem install bundler
before_script:
  - "./bin/ci/install_on_debian.sh"
  - until sudo lsof -i:5672; do echo "Waiting for RabbitMQ to start..."; sleep 1; done
matrix:
  include:
    - rvm: "2.6.0"
    - rvm: "2.5.1"
    - rvm: "2.4.2"
    - rvm: "2.3.5"
    - rvm: "jruby-9.2.5.0"
  allow_failures:
    rvm:
      - "jruby-9.2.5.0"
      - ruby-head

services:
  - rabbitmq
