language: ruby
cache: bundler
before_install:
  - gem install bundler
matrix:
  include:
    - rvm: 2.4.2
    - rvm: 2.3.5
    - rvm: 2.2.8
    - rvm: 2.1
    - rvm: 2.0
    - rvm: jruby-9.1.14.0
      jdk: oraclejdk8
      env:
        - JRUBY_OPTS='--debug'

services:
  - rabbitmq
