language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
matrix:
  include:
    - rvm: 2.4.1
    - rvm: 2.3.4
    - rvm: 2.2.7
    - rvm: 2.1
    - rvm: 2.0
    - rvm: jruby-9.1.8.0
      jdk: oraclejdk8
      env:
        - JRUBY_OPTS='--debug'

services:
  - rabbitmq
