language: ruby
cache: bundler
before_install: gem i bundler
matrix:
  include:
    - rvm: 2.3.3
    - rvm: 2.2
    - rvm: 2.1
    - rvm: 2.0
    - rvm: jruby-9.1.6.0
      jdk: oraclejdk8
      env:
        - JRUBY_OPTS='--debug'

services:
  - rabbitmq
